# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=254, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='изображене')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='odinass.Category', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name_plural': 'категории',
                'verbose_name': 'категория',
                'ordering': ['title'],
                'default_related_name': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='наименование')),
            ],
            options={
                'verbose_name_plural': 'предложения',
                'verbose_name': 'предложение',
                'ordering': ['title'],
                'default_related_name': 'offers',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=254, verbose_name='валюта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='цена')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='odinass.Offer', verbose_name='предложение')),
            ],
            options={
                'verbose_name_plural': 'цены',
                'verbose_name': 'цена',
                'ordering': ['currency'],
                'default_related_name': 'prices',
            },
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='наименование')),
            ],
            options={
                'verbose_name_plural': 'тип цен',
                'verbose_name': 'тип цены',
                'ordering': ['title'],
                'default_related_name': 'price_types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='название')),
                ('article', models.CharField(blank=True, max_length=254, verbose_name='артикул')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='odinass.Category', verbose_name='категории')),
            ],
            options={
                'verbose_name_plural': 'товары',
                'verbose_name': 'товар',
                'ordering': ['title'],
                'default_related_name': 'products',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='название')),
                ('value_type', models.CharField(blank=True, max_length=254, verbose_name='тип значений')),
            ],
            options={
                'verbose_name_plural': 'свойства',
                'verbose_name': 'свойство',
                'ordering': ['title'],
                'default_related_name': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='название')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='odinass.Property', verbose_name='свойство')),
            ],
            options={
                'verbose_name_plural': 'значения свойства',
                'verbose_name': 'значение свойства',
                'ordering': ['title'],
                'default_related_name': 'property_values',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='property_values',
            field=models.ManyToManyField(blank=True, related_name='products', to='odinass.PropertyValue', verbose_name='значения свойства'),
        ),
        migrations.AddField(
            model_name='price',
            name='price_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='odinass.PriceType', verbose_name='тип цены'),
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='odinass.Product', verbose_name='товар'),
        ),
    ]
