# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='название')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='odinass.Category', verbose_name='родительская категория')),
            ],
            options={
                'default_related_name': 'categories',
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='название')),
                ('article', models.CharField(blank=True, max_length=254, verbose_name='артикул')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='odinass.Category', verbose_name='категории')),
            ],
            options={
                'default_related_name': 'products',
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='название')),
            ],
            options={
                'default_related_name': 'properties',
                'verbose_name': 'свойство',
                'verbose_name_plural': 'свойства',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='название')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='odinass.Property', verbose_name='свойство')),
            ],
            options={
                'default_related_name': 'property_values',
                'verbose_name': 'значение свойства',
                'verbose_name_plural': 'значениея свойства',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='property_values',
            field=models.ManyToManyField(blank=True, related_name='products', to='odinass.PropertyValue', verbose_name='значения свойства'),
        ),
    ]
