# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 23:13
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPG', keep_meta=True, null=True, quality=0, size=[1024, 1024], upload_to='whatever', verbose_name='изображение'),
        ),
    ]
