# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0002_pricetype_sales_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=254, verbose_name='название')),
            ],
            options={
                'default_related_name': 'warehouses',
                'verbose_name_plural': 'склады',
                'verbose_name': 'склад',
                'ordering': ['title'],
            },
        ),
    ]
