# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0002_auto_20171008_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyvalue',
            options={'ordering': ['title'], 'verbose_name': 'значение свойства', 'verbose_name_plural': 'значения свойства'},
        ),
        migrations.AddField(
            model_name='property',
            name='value_type',
            field=models.CharField(blank=True, max_length=254, verbose_name='тип значений'),
        ),
    ]
