# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 23:20
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms
import odinass.models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=0, size=[1024, 1024], upload_to=odinass.models.generate_upload_path, verbose_name='изображение'),
        ),
    ]
