# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0003_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='остаток')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rests', to='odinass.Offer', verbose_name='предложение')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rests', to='odinass.Warehouse', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'остаток',
                'default_related_name': 'rests',
                'verbose_name_plural': 'остатки',
            },
        ),
    ]
