# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0003_auto_20171215_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='выбрано'),
        ),
    ]
