# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0004_warehouse_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='traceback',
            field=models.TextField(blank=True, verbose_name='traceback'),
        ),
    ]
