# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0005_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='filename',
            field=models.CharField(db_index=True, max_length=254, verbose_name='название файла'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.IntegerField(choices=[(1, 'обрабатывается'), (2, 'завершено'), (3, 'завершено с ошибкой')], default=1, verbose_name='статус'),
        ),
    ]
