# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0006_product_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetype',
            name='sales_type',
        ),
        migrations.AddField(
            model_name='pricetype',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, verbose_name='по умолчанию'),
        ),
    ]
