# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0006_auto_20171203_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created'], 'verbose_name': 'лог', 'verbose_name_plural': 'логи'},
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=508, verbose_name='название'),
        ),
    ]
