# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def apply_migration(apps, schema_editor):
    Product = apps.get_model('odinass', 'Product')
    for product in Product.objects.all():
        product.category = product.categories.last()
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0007_auto_20180205_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_rename', to='odinass.Category', verbose_name='категория'),
        ),
        migrations.RunPython(apply_migration),
    ]
