# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0009_auto_20180220_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, verbose_name='избранный'),
        ),
    ]
