# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0010_product_is_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyvalue',
            options={'ordering': ['property__title', 'title'], 'verbose_name': 'значение свойства', 'verbose_name_plural': 'значения свойства'},
        ),
    ]
