# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-22 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0011_auto_20180223_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
            ],
            options={
                'verbose_name_plural': 'новинки',
                'verbose_name': 'новинка',
                'proxy': True,
                'indexes': [],
            },
            bases=('odinass.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок'),
        ),
    ]
