# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-22 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0012_auto_20180422_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorder',
            options={'ordering': ['order'], 'verbose_name': 'новинка', 'verbose_name_plural': 'новинки'},
        ),
    ]
