# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-30 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0013_auto_20180422_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='odinass.Product', verbose_name='товар')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name_plural': 'новинки',
                'verbose_name': 'новинка',
            },
        ),
    ]
