# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0015_auto_20181117_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_weight',
            field=models.BooleanField(default=False, verbose_name='используется для веса'),
        ),
    ]
