# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 20:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0016_property_is_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='описание'),
        ),
    ]
