# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-27 18:55
from __future__ import unicode_literals

from django.db import migrations, models, transaction

from pytils.translit import slugify


def gen_path(apps, schema_editor):
    Category = apps.get_model('odinass', 'category')
    while Category.objects.filter(path__isnull=True).exists():
        with transaction.atomic():
            for row in Category.objects.filter(path__isnull=True)[:1000]:
                slug_list = []
                instance = row
                while instance is not None:
                    slug_list.append(instance.slug)
                    instance = instance.parent
                row.path = '/'.join(reversed(slug_list))
                row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0019_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='полный путь'),
        ),
        migrations.RunPython(gen_path, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.TextField(blank=True, db_index=True, verbose_name='полный путь'),
        )
    ]
