# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-24 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0023_auto_20220330_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Условия акции'),
        ),
    ]
