# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-29 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0025_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='keywords',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Дескрипшен'),
        ),
    ]
