# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-29 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0026_auto_20220629_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='tags',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Тэги товара'),
        ),
    ]
