# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-29 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0031_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='offer',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
