# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0032_auto_20220629_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tegs', models.CharField(max_length=100, verbose_name='Тэги товара')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_tags', to='odinass.Offer', verbose_name='Предложение товара')),
            ],
        ),
    ]
