# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-02 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0033_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Дескрипшен'),
        ),
        migrations.AddField(
            model_name='category',
            name='metatitle',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Тайтл'),
        ),
    ]
