# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-02 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0034_auto_20221102_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='h1_title',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Дескрипшен'),
        ),
    ]
