# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 23:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=36, verbose_name='идентификатор')),
                ('status', models.CharField(choices=[('pending', 'Создан'), ('waiting_for_capture', 'Ожидает подтверждения'), ('succeeded', 'Завершен'), ('canceled', 'Отменен')], db_index=True, default='pending', max_length=20, verbose_name='статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='сумма')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('BYN', 'Белорусский рубль'), ('CNY', 'Китайский юань'), ('KZT', 'Казахстанский тенге'), ('UAH', 'Украинская гривна')], default='RUB', max_length=3, verbose_name='валюта')),
                ('payment_method', models.CharField(choices=[('yandex_money', 'Яндекс.Деньги'), ('bank_card', 'Банковская карта'), ('sberbank', 'Сбербанк Онлайн'), ('cash', 'Наличными в терминале'), ('mobile_balance', 'Баланс мобильного телефона'), ('psb', 'Интернет-банк Промсвязьбанка'), ('qiwi', 'QIWI Кошелек'), ('webmoney', 'Webmoney'), ('alfabank', 'Альфа-Клик'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('installments', 'Через сервис "Заплатить по частям"')], default='yandex_money', max_length=20, verbose_name='способ оплаты')),
                ('description', models.TextField(blank=True, verbose_name='описание транзакции')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='дополнительные данные')),
                ('receipt_registration', models.CharField(blank=True, choices=[('pending', 'Создан'), ('succeeded', 'Завершен'), ('canceled', 'Отменен')], db_index=True, max_length=20, verbose_name='статус доставки чека в онлайн-кассу')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='время создания')),
                ('captured_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='время подтверждения')),
                ('expires_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='время отмены удержания')),
                ('order_id', models.TextField(blank=True, help_text='Внутренний номер заказа/товара.', max_length=100, verbose_name='ID заказа')),
                ('payer_email', models.EmailField(blank=True, max_length=100, verbose_name='email плательщика')),
                ('payer_phone', models.CharField(blank=True, max_length=20, verbose_name='телефон плательщика')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yandex_kassa_payments', to=settings.AUTH_USER_MODEL, verbose_name='плательщик')),
            ],
            options={
                'get_latest_by': 'pk',
                'verbose_name_plural': 'платежи',
                'verbose_name': 'платёж',
                'ordering': ['-pk'],
                'default_related_name': '%(app_label)s_%(model_name)ss',
            },
        ),
    ]
