# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_kassa', '0002_auto_20181111_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, help_text='Внутренний номер заказа/товара.', max_length=100, verbose_name='ID заказа'),
        ),
    ]
