# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0006_product_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='odinass.PriceType', verbose_name='тип цены')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'default_related_name': 'profiles',
                'verbose_name_plural': 'профили',
                'verbose_name': 'профиль',
            },
        ),
    ]
