# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180227_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='почта'),
        ),
    ]
