# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-22 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_office_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
    ]
