# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-20 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180422_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
    ]
