# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-30 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_office_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_address',
            field=models.TextField(blank=True, verbose_name='юридический адрес'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=254, verbose_name='телефон'),
        ),
    ]
