# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-19 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180830_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='приход'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='yandex_money.Payment', verbose_name='платёж'),
        ),
    ]
