# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-19 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20180919_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_order', to='yandex_money.Payment', verbose_name='платёж'),
        ),
    ]
