# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='почтовый индекс'),
        ),
    ]
