# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.IntegerField(choices=[(1, 'Самовывоз')], default=1, verbose_name='тип доставки'),
        ),
    ]
