# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-22 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_copy_from_profile'),
        ('orders', '0018_auto_20200108_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsettings',
            name='group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='price_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='GroupSettings',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
