# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='название')),
                ('css', models.CharField(max_length=254, verbose_name='css class')),
                ('content', models.TextField(blank=True, verbose_name='контент')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'страницы',
                'default_related_name': 'pages',
                'verbose_name': 'страница',
                'ordering': ['order'],
            },
        ),
    ]
