# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170924_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='css',
        ),
        migrations.AddField(
            model_name='page',
            name='icon',
            field=models.CharField(blank=True, max_length=254, verbose_name='иконка'),
        ),
    ]
