# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170924_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='slug'),
        ),
    ]
