# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 06:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170924_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='название')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='контент')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'блог',
                'default_related_name': 'blogs',
                'verbose_name_plural': 'блоги',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='название')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='изображене')),
                ('url', models.CharField(blank=True, max_length=254, verbose_name='ссылка на страницу')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'слайд',
                'default_related_name': 'slides',
                'verbose_name_plural': 'слайды',
                'ordering': ['order'],
            },
        ),
    ]
