# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-22 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_blog_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='background',
            field=models.CharField(default='#FFFFFF', max_length=10, verbose_name='фон'),
        ),
        migrations.AddField(
            model_name='slider',
            name='content',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='slider',
            name='discount',
            field=models.CharField(blank=True, max_length=254, verbose_name='скидка'),
        ),
    ]
