# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-22 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180422_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='background',
            field=models.CharField(default='#2C7FAE', max_length=10, verbose_name='фон'),
        ),
    ]
