# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-31 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_vkvidjet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkvidjet',
            name='status',
            field=models.BooleanField(default=False, help_text='Если есть другие активные виджеты, то необходимо отключить данный параметр', verbose_name='На все страницы'),
        ),
    ]
