# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-21 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_vkvidjet_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('img', models.ImageField(blank=True, upload_to='frontend/images')),
            ],
            options={
                'verbose_name_plural': 'Изменение футера',
                'verbose_name': 'Изменение футера',
            },
        ),
    ]
