# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-23 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20220423_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('sort', models.SmallIntegerField(unique=True, verbose_name='Порядок сортировки')),
                ('social', models.CharField(max_length=150, verbose_name='Код иконки')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Социальные иконки в футере',
                'verbose_name_plural': 'Социальные иконки в футере',
            },
        ),
    ]
