# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-23 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Логотип', 'Логотип')], max_length=20, unique=True, verbose_name='Название')),
                ('img', models.ImageField(upload_to='frontend/images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотип',
            },
        ),
    ]
