# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-23 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_headerlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1', 'Левый верх'), ('2', 'Правый верх'), ('3', 'Левый низ'), ('4', 'Правый низ')], max_length=10, verbose_name='Название')),
                ('img', models.ImageField(upload_to='frontend/images/', verbose_name='Картинка')),
                ('video', models.FileField(upload_to='frontend/videos/', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Картинки и видео для основных категорий',
                'verbose_name_plural': 'Картинки и видео для основных категорий',
            },
        ),
    ]
