# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-23 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_imgcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgcategory',
            name='video',
            field=models.FileField(blank=True, upload_to='frontend/videos/', verbose_name='Видео'),
        ),
    ]
