# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-23 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20220423_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgcategory',
            name='title',
            field=models.CharField(choices=[('Левый верх', 'Левый верх'), ('Правый верх', 'Правый верх'), ('Левый низ', 'Левый низ'), ('Правый низ', 'Правый низ')], max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
