# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-26 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20220425_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imgcategory',
            options={'ordering': ['title'], 'verbose_name': 'Картинки и видео для основных категорий', 'verbose_name_plural': 'Картинки и видео для основных категорий'},
        ),
    ]
