# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-26 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20220426_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerimg',
            name='img',
            field=models.ImageField(blank=True, upload_to='slider/'),
        ),
    ]
