# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20220426_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlogo',
            name='img',
            field=models.ImageField(upload_to='slider/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imgcategory',
            name='img',
            field=models.ImageField(upload_to='slider/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='imgcategory',
            name='video',
            field=models.FileField(blank=True, upload_to='slider/', verbose_name='Видео'),
        ),
    ]
