# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-26 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20220426_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerimg',
            name='img',
        ),
        migrations.AddField(
            model_name='footerimg',
            name='title',
            field=models.CharField(choices=[('Футер', 'Футер')], default='Футер', max_length=10, unique=True),
        ),
    ]
