# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-23 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20220426_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorTopHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1', 'Цвет')], max_length=15, unique=True)),
                ('color', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Цвет полоски меню',
                'verbose_name_plural': 'Цвет полосок меню',
            },
        ),
    ]
