# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-23 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_colortophead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colortophead',
            options={'verbose_name': 'Цвет полоски меню', 'verbose_name_plural': 'Цвет полоски меню'},
        ),
        migrations.AlterField(
            model_name='colortophead',
            name='title',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
