# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-07 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_menupage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menupage',
            name='page',
        ),
        migrations.AddField(
            model_name='page',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='pages.MenuPage', verbose_name='Вкладка меню'),
        ),
    ]
