# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-08 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20220707_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='in_menu',
            field=models.BooleanField(default=False, verbose_name='Закрепить в основное меню'),
        ),
    ]
