# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-22 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_page_in_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('url_img', models.ImageField(upload_to='page_image/', verbose_name='Изображение')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_page', to='pages.Page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Картинка на странице',
                'verbose_name_plural': 'Картинки на странице',
            },
        ),
    ]
