# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-22 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_imagepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepage',
            name='url_img',
            field=models.ImageField(upload_to='slider/', verbose_name='Изображение'),
        ),
    ]
