# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20220722_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='Выводимое название')),
                ('img', models.ImageField(upload_to='slider/', verbose_name='Картинка')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка на категорию')),
            ],
            options={
                'verbose_name': 'Вывод категорий на главной',
                'verbose_name_plural': 'Вывод категорий на главной',
            },
        ),
    ]
