# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-22 13:39
from __future__ import unicode_literals

from django.db import migrations


def copy_from_profile(apps, schema_editor):
    """
    Копируем данные из модели Profile в модель пользователя.
    """
    User = apps.get_model('accounts', 'User')

    for user in User.objects.all():
        user.price_type = user.profile.price_type
        user.company = user.profile.company
        user.company_address = user.profile.company_address
        user.inn = user.profile.inn
        user.phone = user.profile.phone
        user.is_wholesaler = user.groups.filter(name='Оптовик').exists()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221222_1639'),
    ]

    operations = [
        migrations.RunPython(
            copy_from_profile,
            reverse_code=migrations.RunPython.noop
        ),
    ]
